<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir cancion a la lista</title>
</head>
<body>
    <?php
    // echo var_dump($_GET);
    $list = PlaylistRepository::getListById($_GET['list']);
    echo '<div>';
    echo '<h2>'.$list->getName().'</h2>';
    echo '<h4>(canciones en la lista: '.sizeof($list->getSongs()).')</h4>';
    $totalDuration = 0;
    foreach ($list->getSongs() as $songId) {
            $song = SongRepository::getSongById($songId);
            if ($song != null) {
                echo '<p>'.$song->getTitle().'</p>';
                $totalDuration += $song->getDuration();
            }
    }
    echo '<h4>(duración total: '.$totalDuration.')</h4>';

    echo '<form action="index.php?c=list&list='.$_GET['list'].'" method="POST">';
    echo '<input list="canciones" name="songTitle">';
    echo '<datalist id="canciones">';
    $songsIds = SongRepository::getAllSongsIds();
    foreach ($songsIds as $songId) {
        echo '<option value="' . SongRepository::getSongById($songId)->getTitle() . '">';
    }
    echo '</datalist>';
    echo '<input type="submit" name="addThisSong" value="Añadir" />';
    echo '</form>';
    echo '</div>';

    ?>
</body>
</html>