<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir cancion a la lista</title>
</head>
<body>
    <?php
    $list = PlaylistRepository::getListById($_GET['list']);
    echo '<div>';
    echo '<h2>'.$list->getName().'</h2>';
    echo '<h4>(canciones en la lista: '.sizeof($list->getSongsIds()).')</h4>';
    $list->loadSongs();
    foreach ($list->getSongsObjects() as $song) {
            if ($song != null) {
                echo '<p>'.$song->getTitle().'</p>';
            }
    }
    echo '<h4>(duración total: '.PlaylistRepository::getPlaylistDuration($list->getId()).')</h4>';

    echo '<form action="index.php?c=list&list='.$_GET['list'].'" method="POST">';
    echo '<input list="canciones" name="idSong" id="input-datalist">';
    echo '<datalist id="canciones">';
    $songsIds = SongRepository::getAllSongsIds();
    $unicodeChar = "\u{200B}";
    foreach ($songsIds as $songId) {        
        /* --------------- parseando string para sacar titulo u autor --------------- */
        echo '<option value="'. SongRepository::getSongById($songId)->getTitle() . ' -'. $unicodeChar . ' ' . SongRepository::getSongById($songId)->getAuthor() . '">';
        /* ------------------- usando datalist sin id y javascript ------------------ */
        // echo '<option data-value="'.$songId.'" value="'. SongRepository::getSongById($songId)->getTitle() . ' - ' . SongRepository::getSongById($songId)->getAuthor() .'" />';
    }
    echo '</datalist>';
    // echo '<input type="hidden" id="idSecreta" name="idSecreta" value="0" />'; // <- usando datalist sin id y javascript
    echo '<input type="submit" name="addThisSong" value="Añadir" />';
    echo '</form>';
    echo '</div>';

    ?>
    <script> // <- usando datalist sin id y javascript
        /*
        function setHiddenValue() {
            const inputDatalist = document.getElementById('input-datalist');
            const dataList = document.getElementById('canciones');
            const opcionSeleccionada = document.querySelector("#canciones option[value='" + inputDatalist.value + "']");
            const atributoDataValue = opcionSeleccionada.getAttribute("data-value");
            console.log(atributoDataValue);
            document.getElementById('idSecreta').value = atributoDataValue;
        }
        document.getElementById('input-datalist').addEventListener('change', setHiddenValue );
        */
    </script>
</body>
</html>