<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explorar Listas de Reproducción</title>
</head>
<body>
<div class="container" style="background-color:#e3e3f3;">
    <?php

        if (isset($_SESSION['user'])) {

            $lists = PlaylistRepository::getAllLists();
            
            echo '<span style="display:flex;flex-wrap:wrap">';
            echo ViewRepository::printPlaylists($lists);
            echo '</span>';
        }
    ?>
</div>
</body>
</html>