<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explorar Listas de Reproducción</title>
</head>
<body>
<div class="container">
    <?php

        if (isset($_SESSION['user'])) {

            echo ViewRepository::printUserHeader($_SESSION['user']);

            $lists = PlaylistRepository::getAllLists();
            
            echo '<span style="display:flex">';
            echo ViewRepository::printPlaylists($lists);
            echo '</span>';

            echo '<br><a href="index.php?c=list&createList=1">Crear nueva lista</a><br>';
            echo '<a href="index.php?c=song&createSong=1">Crear nueva canción</a><br>';
            // echo '<a href="index.php?c=list&discardNewPlaylist=1">Desechar nueva lista</a><br>';
            echo '<a href="index.php?c=search">Buscador de canciones</a><br>';
            echo '<a href="index.php">Volver</a><br>';
        }
    ?>
</div>
</body>
</html>