<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ver lista de reproducción</title>
    <style>        
        .active a{color:#5DB0E6;text-decoration:none;}
    </style>
</head>
<body>
    <div class="container" style="background-color: #f2f2e2;">
        <?php
            $list = PlaylistRepository::getListById($_GET['list']);
            $showDelete = $list->getCreator() == $_SESSION['user']->getId();
            echo '<div>';
            echo '<h2>Lista: '.$list->getName().'</h2>';
            echo '<h3>creada por '.UserRepository::getUserById($list->getCreator())->getName().'</h3>';
            echo '<h4>(canciones en la lista: '.sizeof($list->getSongsIds()).')</h4><ul>';
            $list->loadSongs();
            foreach ($list->getSongsObjects() as $song) {
                    if ($song != null) {                        
                        echo '<li><p>'.$song->getTitle().' by: '.$song->getAuthor().'. (duración '.ViewRepository::printDuration($song->getDuration()).')';
                        if ($showDelete) {
                            echo '<a href="index.php?c=list&remove='.$song->getId().'&list='.$list->getId().'">X</a>';
                        }
                        if ($song->getMp3File() !== '<no file>') {
                            echo '<audio controls style="height: 1em"><source src="upload/'.$song->getMp3File().'" type="audio/mpeg"></audio></p></li>';
                        }
                    }
            }
            echo '</ul><h4>(duración total: ';
            echo ViewRepository::printDuration(PlaylistRepository::getPlaylistDuration($list->getId()));
            echo ')</h4>';
            // echo PlaylistRepository::playFullList($list->getMp3List());
            echo ViewRepository::printFullPlayback($list);
            echo '<a href="index.php?c=list&addSong=1&list='.$list->getId().'">Añadir canción</a><br>';
            echo '<a href="index.php">Cerrar</a>';
            echo '</div>';
        ?>
    </div>
    
</body>
</html>