<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ver lista de reproducción</title>
    <style>        
        .active a{color:#5DB0E6;text-decoration:none;}
    </style>
</head>
<body>
    <div class="container" style="background-color: #f2f2e2;">
        <?php
            $list = PlaylistRepository::getListById($_GET['list']);
            echo ViewRepository::printDetailedPlaylist($list);
            
            echo '<a href="index.php?c=list&addSong=1&list='.$list->getId().'">Añadir canción</a><br>';
            echo '<a href="index.php">Cerrar</a>';
            echo '</div>';
        ?>
    </div>
    
</body>
</html>