<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Registro en Blog</title>
</head>

<body>
    <form action="index.php?c=user" method="POST" style="text-align: center;">
        <div>
            <fieldset style="display: inline-block;">
                <input type="text" class="form-control my-2" name="user" placeholder="Nombre de usuario" required /><br>
                <input type="password" class="form-control my-2" name="password" placeholder="Contraseña" required /><br>&nbsp;<br>
                <input type="submit" class="form-control bg-primary text-white" name="login" value="Entrar" /><br>
            </fieldset>
        </div>
        <!-- <a href="index.php?invitado=1&c=user">invitado</a>&nbsp; -->
        <a href="index.php?registroFrm=1&c=user">registrarse</a>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>