<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear nueva lista</title>

</head>

<body>
    <div class="container">
        <form action="index.php?c=list" method="POST">
            <label for="name">Nombre de la lista</label>
            <input type="text" id="nameField" name="name" <?php if (isset($_SESSION['listaTemporal'])) echo 'value="' . $_SESSION['listaTemporal']->getName() . '"'; ?> required />
            <br>
            <?php
            if (isset($_SESSION['creandoLista'])) {
                echo '<input type="submit" name="saveName" value="Cambiar nombre">';
            } else {
                echo '<input type="submit" name="saveName" value="Confirmar nombre">';
            }
            ?>
        </form>
        <?php if (isset($_SESSION['creandoLista'])) {
        ?>
            <form action="index.php?c=list" method="POST">
                <?php
                if (isset($_SESSION['listaTemporal'])) {
                    $list = $_SESSION['listaTemporal'];
                    $list->loadSongs();
                    foreach ($list->getSongsObjects() as $song) {
                        if ($song != null) {
                            echo '<p>' . $song->getTitle() . '</p>';
                        }
                    }
                }
                ?>
                <a href="index.php?c=song&createSong=1">Nueva canción</a><br>
                <a href="index.php?c=search">Buscador de canciones</a><br>
                <input type="submit" name="newlist" value="Guardar esta lista">
            </form><br>
            <a href="index.php?c=list&discardNewPlaylist=1">Desechar esta lista</a><br>
        <?php
        }
        ?>
        <a href="index.php">Volver</a>

    </div>
</body>

</html>