<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear nueva canción</title>
</head>
<body>
    <div class="container">
        <h1>Crear una nueva canción:</h1>
        <form action="index.php?c=song" method="POST" enctype="multipart/form-data">
            <label for="title">Título<input type="text" name="title" required /><br></label>            
            <label for="author">Autor<input type="text" name="author" required /><br></label>
            <label for="duration">Duracion<input type="number" name="duration" value="0" /><br></label>            
            <label for="mp3file">Subir archivo<input type="file" name="mp3file" /><br></label>
            <?php 
            if (!isset($_SESSION['creandoLista'])) {
                $lists = PlaylistRepository::getListsByUser($_SESSION['user']->getId());
                if (sizeof($lists) > 0){
                    echo '<label for="idPlaylist">Añadir a lista:';
                    echo '<select name="idPlaylist">';
                    foreach ($lists as $list) {
                        echo '<option value = '.$list->getId().'>'.$list->getName().'</option>';
                    }
                    echo '</select></label><br>';
                }
            }
            ?>
            <input type="submit" name="createSong" value="Crear esta canción">

        </form>
        <a href="index.php?c=list">Volver</a>
    </div>    
</body>
</html>